name: DB Migrate

on:
  push:
    branches: [ main ]
    paths:
      - 'migrate/**'         # only when migration scripts change
      - '.github/workflows/db-migrate.yml'
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Start SSH agent with CI key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.GCE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Ensure rsync is installed on VM
        run: |
          ssh ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }} "command -v rsync >/dev/null 2>&1 || (sudo apt-get update && sudo apt-get install -y rsync)"

      - name: Sync migrations to VM (/opt/nano/migrate)
        run: |
          rsync -avz --delete migrate/ ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }}:/opt/nano/migrate/

      - name: Run Flyway migrate on VM
        run: |
          ssh ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }} "sudo /usr/local/bin/flyway -configFiles=/etc/flyway.conf -X migrate"

      - name: Show Flyway info (after)
        if: always()
        run: |
          ssh ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }} "sudo /usr/local/bin/flyway -configFiles=/etc/flyway.conf info"
