name: DB Migrate

on:
  push:
    branches: [ main ]
    paths:
      - 'migrate/**'
      - '.github/workflows/db-migrate.yml'
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent with CI key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.GCE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Prepare target dir (no sudo needed if /opt/nano owned by deployer)
        run: |
          ssh ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }} "mkdir -p /opt/nano/migrate && rm -rf /opt/nano/migrate/*"

      - name: Copy migrations via scp
        run: |
          scp -r migrate/* ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }}:/opt/nano/migrate/

      - name: Run Flyway migrate (no sudo, pass config via flags)
        run: |
          ssh ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }} "\
            /usr/local/bin/flyway \
              -url='${{ secrets.DB_URL }}' \
              -user='${{ secrets.DB_USER }}' \
              -password='${{ secrets.DB_PASS }}' \
              -locations='filesystem:/opt/nano/migrate' \
              -sqlMigrationPrefix='V_' \
              -repeatableSqlMigrationPrefix='R__' \
              -sqlMigrationSeparator='__' \
              -sqlMigrationSuffixes='.sql' \
              -baselineOnMigrate=true \
              -outOfOrder=false \
              -X migrate \
          "

      - name: Flyway info (after)
        if: always()
        run: |
          ssh ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_IP }} "\
            /usr/local/bin/flyway \
              -url='${{ secrets.DB_URL }}' \
              -user='${{ secrets.DB_USER }}' \
              -password='${{ secrets.DB_PASS }}' \
              -locations='filesystem:/opt/nano/migrate' \
              -sqlMigrationPrefix='V_' \
              -repeatableSqlMigrationPrefix='R__' \
              -sqlMigrationSeparator='__' \
              -sqlMigrationSuffixes='.sql' \
              info \
          "
